language: python
dist: xenial
python:
  - "3.7"
  - "3.6"

stages:
  - quality
  - test
  - publish

before_install:
  - pip install poetry

install:
  - poetry install

script: make test

jobs:
  include:
    - stage: quality
      name: Lint
      script: make lint
    - name: Type
      script: make type
    - stage: publish
      name: Publish
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
      if: tag IS present

after_success:
  poetry run coveralls
